// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "hello_pepo",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "hello_pepo",
            targets: ["AppModule"],
            bundleIdentifier: "appledeveloperacademy.hello-pepo",
            teamIdentifier: "2QB643XL72",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .palette),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("3DModels"),
		.process("Sounds")
            ]
        ),
    ],
    swiftLanguageVersions: [.v6]
)
